<a href="https://colab.research.google.com/github/ppant/CodingBat/blob/main/Practice_on_colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([1,6,3,1,7])

In [3]:
x

array([1, 6, 3, 1, 7])

In [4]:
bool_x = x == 5

In [5]:
bool_x

array([False, False, False, False, False])

In [6]:
x = np.array([6, 4, 5, 7])
y = np.array([5, 1, 8, 7])

In [9]:
print (np.corrcoef(x,y))

[[1.         0.62554324]
 [0.62554324 1.        ]]


In [19]:
x = np.array([10, 15, 22, 13, 17, 20, 8])


In [20]:
x

array([10, 15, 22, 13, 17, 20,  8])

In [23]:
x_small = x[x < 17]


In [24]:
x_small

array([10, 15, 13,  8])